services:
  backend:
    build: ./flight_backend
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgres://flights_user:password@db:5432/flights?sslmode=disable
      - JWT_SECRET=super-secret-key-here
      - JWT_TTL=1h
      - LOGIN_RATE_RPS=3
      - LOGIN_BURST=10
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=flights_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flights
    ports:
      - "5432:5432"
    volumes:
      # 1) данные БД (чтобы не пропали между перезапусками)
      - db_data:/var/lib/postgresql/data
      # 2) наши скрипты инициализации
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/flights_dump.sql:/docker-entrypoint-initdb.d/02_flights_dump.sql
      # если есть seed_dev.sql — можно третьей строкой
      # - ./db/seed_dev.sql:/docker-entrypoint-initdb.d/03_seed_dev.sql

volumes:
  db_data: