services:
  web:
    ports:
      - "8081:80"   # сайт будет на http://localhost:8081

  backend:
    ports:
      - "8080:8080" # опционально (удобно дергать API напрямую)

  db:
    ports:
      - "5433:5432" # опционально (если хотите подключаться psql/IDE)